//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.14.0
//     from Assets/Blueprints/InputActions/IAARInteraction.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

/// <summary>
/// Provides programmatic access to <see cref="InputActionAsset" />, <see cref="InputActionMap" />, <see cref="InputAction" /> and <see cref="InputControlScheme" /> instances defined in asset "Assets/Blueprints/InputActions/IAARInteraction.inputactions".
/// </summary>
/// <remarks>
/// This class is source generated and any manual edits will be discarded if the associated asset is reimported or modified.
/// </remarks>
/// <example>
/// <code>
/// using namespace UnityEngine;
/// using UnityEngine.InputSystem;
///
/// // Example of using an InputActionMap named "Player" from a UnityEngine.MonoBehaviour implementing callback interface.
/// public class Example : MonoBehaviour, MyActions.IPlayerActions
/// {
///     private MyActions_Actions m_Actions;                  // Source code representation of asset.
///     private MyActions_Actions.PlayerActions m_Player;     // Source code representation of action map.
///
///     void Awake()
///     {
///         m_Actions = new MyActions_Actions();              // Create asset object.
///         m_Player = m_Actions.Player;                      // Extract action map object.
///         m_Player.AddCallbacks(this);                      // Register callback interface IPlayerActions.
///     }
///
///     void OnDestroy()
///     {
///         m_Actions.Dispose();                              // Destroy asset object.
///     }
///
///     void OnEnable()
///     {
///         m_Player.Enable();                                // Enable all actions within map.
///     }
///
///     void OnDisable()
///     {
///         m_Player.Disable();                               // Disable all actions within map.
///     }
///
///     #region Interface implementation of MyActions.IPlayerActions
///
///     // Invoked when "Move" action is either started, performed or canceled.
///     public void OnMove(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnMove: {context.ReadValue&lt;Vector2&gt;()}");
///     }
///
///     // Invoked when "Attack" action is either started, performed or canceled.
///     public void OnAttack(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnAttack: {context.ReadValue&lt;float&gt;()}");
///     }
///
///     #endregion
/// }
/// </code>
/// </example>
public partial class @IAARInteraction: IInputActionCollection2, IDisposable
{
    /// <summary>
    /// Provides access to the underlying asset instance.
    /// </summary>
    public InputActionAsset asset { get; }

    /// <summary>
    /// Constructs a new instance.
    /// </summary>
    public @IAARInteraction()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""IAARInteraction"",
    ""maps"": [
        {
            ""name"": ""ARPlacement"",
            ""id"": ""0aa4714b-b8a0-4996-83d6-5623dc0624e2"",
            ""actions"": [
                {
                    ""name"": ""PlaceDragon"",
                    ""type"": ""Button"",
                    ""id"": ""ccde4910-32cd-428c-a7a0-dd1cef5b7197"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""AlignmentDone"",
                    ""type"": ""Button"",
                    ""id"": ""7c1935e0-512e-43bc-9c88-d1107d75eaeb"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""AutoSpawnAlign"",
                    ""type"": ""Button"",
                    ""id"": ""1ae10110-1335-438e-aebe-4d1550f53b08"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""1D Axis"",
                    ""id"": ""86118984-363f-4758-8829-62874885d34d"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PlaceDragon"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""4159aa57-00c7-4eda-9176-6ce893ce970f"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PlaceDragon"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""1D Axis"",
                    ""id"": ""7bd23b5e-5b84-4d93-ac0f-3eca11d4b199"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AlignmentDone"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""ecc419b1-a6e6-4254-9418-0deace0aa248"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AlignmentDone"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""d89729c9-3918-4c72-9f84-19f296632483"",
                    ""path"": ""<Gamepad>/{Back}"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AutoSpawnAlign"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ab45ce5a-a0d4-4438-9bc8-6136c35a5d08"",
                    ""path"": ""<Keyboard>/p"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AutoSpawnAlign"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // ARPlacement
        m_ARPlacement = asset.FindActionMap("ARPlacement", throwIfNotFound: true);
        m_ARPlacement_PlaceDragon = m_ARPlacement.FindAction("PlaceDragon", throwIfNotFound: true);
        m_ARPlacement_AlignmentDone = m_ARPlacement.FindAction("AlignmentDone", throwIfNotFound: true);
        m_ARPlacement_AutoSpawnAlign = m_ARPlacement.FindAction("AutoSpawnAlign", throwIfNotFound: true);
    }

    ~@IAARInteraction()
    {
        UnityEngine.Debug.Assert(!m_ARPlacement.enabled, "This will cause a leak and performance issues, IAARInteraction.ARPlacement.Disable() has not been called.");
    }

    /// <summary>
    /// Destroys this asset and all associated <see cref="InputAction"/> instances.
    /// </summary>
    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindingMask" />
    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.devices" />
    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.controlSchemes" />
    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Contains(InputAction)" />
    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.GetEnumerator()" />
    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    /// <inheritdoc cref="IEnumerable.GetEnumerator()" />
    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Enable()" />
    public void Enable()
    {
        asset.Enable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Disable()" />
    public void Disable()
    {
        asset.Disable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindings" />
    public IEnumerable<InputBinding> bindings => asset.bindings;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindAction(string, bool)" />
    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindBinding(InputBinding, out InputAction)" />
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // ARPlacement
    private readonly InputActionMap m_ARPlacement;
    private List<IARPlacementActions> m_ARPlacementActionsCallbackInterfaces = new List<IARPlacementActions>();
    private readonly InputAction m_ARPlacement_PlaceDragon;
    private readonly InputAction m_ARPlacement_AlignmentDone;
    private readonly InputAction m_ARPlacement_AutoSpawnAlign;
    /// <summary>
    /// Provides access to input actions defined in input action map "ARPlacement".
    /// </summary>
    public struct ARPlacementActions
    {
        private @IAARInteraction m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public ARPlacementActions(@IAARInteraction wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "ARPlacement/PlaceDragon".
        /// </summary>
        public InputAction @PlaceDragon => m_Wrapper.m_ARPlacement_PlaceDragon;
        /// <summary>
        /// Provides access to the underlying input action "ARPlacement/AlignmentDone".
        /// </summary>
        public InputAction @AlignmentDone => m_Wrapper.m_ARPlacement_AlignmentDone;
        /// <summary>
        /// Provides access to the underlying input action "ARPlacement/AutoSpawnAlign".
        /// </summary>
        public InputAction @AutoSpawnAlign => m_Wrapper.m_ARPlacement_AutoSpawnAlign;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_ARPlacement; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="ARPlacementActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(ARPlacementActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="ARPlacementActions" />
        public void AddCallbacks(IARPlacementActions instance)
        {
            if (instance == null || m_Wrapper.m_ARPlacementActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_ARPlacementActionsCallbackInterfaces.Add(instance);
            @PlaceDragon.started += instance.OnPlaceDragon;
            @PlaceDragon.performed += instance.OnPlaceDragon;
            @PlaceDragon.canceled += instance.OnPlaceDragon;
            @AlignmentDone.started += instance.OnAlignmentDone;
            @AlignmentDone.performed += instance.OnAlignmentDone;
            @AlignmentDone.canceled += instance.OnAlignmentDone;
            @AutoSpawnAlign.started += instance.OnAutoSpawnAlign;
            @AutoSpawnAlign.performed += instance.OnAutoSpawnAlign;
            @AutoSpawnAlign.canceled += instance.OnAutoSpawnAlign;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="ARPlacementActions" />
        private void UnregisterCallbacks(IARPlacementActions instance)
        {
            @PlaceDragon.started -= instance.OnPlaceDragon;
            @PlaceDragon.performed -= instance.OnPlaceDragon;
            @PlaceDragon.canceled -= instance.OnPlaceDragon;
            @AlignmentDone.started -= instance.OnAlignmentDone;
            @AlignmentDone.performed -= instance.OnAlignmentDone;
            @AlignmentDone.canceled -= instance.OnAlignmentDone;
            @AutoSpawnAlign.started -= instance.OnAutoSpawnAlign;
            @AutoSpawnAlign.performed -= instance.OnAutoSpawnAlign;
            @AutoSpawnAlign.canceled -= instance.OnAutoSpawnAlign;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="ARPlacementActions.UnregisterCallbacks(IARPlacementActions)" />.
        /// </summary>
        /// <seealso cref="ARPlacementActions.UnregisterCallbacks(IARPlacementActions)" />
        public void RemoveCallbacks(IARPlacementActions instance)
        {
            if (m_Wrapper.m_ARPlacementActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="ARPlacementActions.AddCallbacks(IARPlacementActions)" />
        /// <seealso cref="ARPlacementActions.RemoveCallbacks(IARPlacementActions)" />
        /// <seealso cref="ARPlacementActions.UnregisterCallbacks(IARPlacementActions)" />
        public void SetCallbacks(IARPlacementActions instance)
        {
            foreach (var item in m_Wrapper.m_ARPlacementActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_ARPlacementActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="ARPlacementActions" /> instance referencing this action map.
    /// </summary>
    public ARPlacementActions @ARPlacement => new ARPlacementActions(this);
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "ARPlacement" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="ARPlacementActions.AddCallbacks(IARPlacementActions)" />
    /// <seealso cref="ARPlacementActions.RemoveCallbacks(IARPlacementActions)" />
    public interface IARPlacementActions
    {
        /// <summary>
        /// Method invoked when associated input action "PlaceDragon" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnPlaceDragon(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "AlignmentDone" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnAlignmentDone(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "AutoSpawnAlign" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnAutoSpawnAlign(InputAction.CallbackContext context);
    }
}
